// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxccoipgmrjfhyoaknbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4Y2NvaXBnbXJqZmh5b2FrbmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxODk0MDcsImV4cCI6MjA3MDc2NTQwN30.9vLJLIY5lMboaQ4ouG7PSZcCIWlTdSasbFBkZa3_28I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});